export var nickCategories = [
	{nick: "Donald Duck", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Daisy Duck", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Tarzan", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Simba", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Elsa", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Anna", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Edsger Dijkstra", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Konrad Zuse", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Alan Turing", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Galileo Galilei", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Johannes Kepler", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Blaise Pascal", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Christiaan Huygens", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Marie Curie", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Isaac Newton", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Robert Boyle", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Gottfried Leibniz", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Johannes Gutenberg", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Leonardo Fibonacci", nickCategory: "view.nickname_categories.category.science"}
];
