export var nickCategories = [
	{nick: "Donald Duck", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Daisy Duck", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Tarzan", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Simba", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Elsa", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Anna", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Kuzco", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Arielle", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Jasmin", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Mulan", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Pluto", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Nemo", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Buzz Lightyear", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Woody", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Lightning McQueen", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Tinkerbell", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Peter Pan", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Cinderella", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Dagobert Duck", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Goofy", nickCategory: "view.nickname_categories.category.disney"},
	{nick: "Edsger Dijkstra", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Konrad Zuse", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Alan Turing", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Galileo Galilei", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Johannes Kepler", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Blaise Pascal", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Christiaan Huygens", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Marie Curie", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Isaac Newton", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Robert Boyle", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Gottfried Leibniz", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Johannes Gutenberg", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Leonardo Fibonacci", nickCategory: "view.nickname_categories.category.science"},
	{nick: "André Ampère", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Archimedes", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Aristoteles", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Leonardo Da Vinci", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Charles Darwin", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Albert Einstein", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Euklid", nickCategory: "view.nickname_categories.category.science"},
	{nick: "Harry Potter", nickCategory: "view.nickname_categories.category.fantasy"},
	{nick: "Hermione Granger", nickCategory: "view.nickname_categories.category.fantasy"},
	{nick: "Ron Weasly", nickCategory: "view.nickname_categories.category.fantasy"},
	{nick: "Darren Shan", nickCategory: "view.nickname_categories.category.fantasy"},
	{nick: "Gollum", nickCategory: "view.nickname_categories.category.fantasy"},
	{nick: "Sauron", nickCategory: "view.nickname_categories.category.fantasy"},
	{nick: "Frodo", nickCategory: "view.nickname_categories.category.fantasy"},
	{nick: "Arwen", nickCategory: "view.nickname_categories.category.fantasy"},
	{nick: "Thorin", nickCategory: "view.nickname_categories.category.fantasy"},
	{nick: "John Snow", nickCategory: "view.nickname_categories.category.fantasy"},
	{nick: "Robb Stark", nickCategory: "view.nickname_categories.category.fantasy"},
	{nick: "Tyrion Lennister", nickCategory: "view.nickname_categories.category.fantasy"},
	{nick: "Cersei Lennister", nickCategory: "view.nickname_categories.category.fantasy"},
	{nick: "Luke Skywalker", nickCategory: "view.nickname_categories.category.fantasy"},
	{nick: "Darth Vader", nickCategory: "view.nickname_categories.category.fantasy"},
	{nick: "Obi-Wan Kenobi", nickCategory: "view.nickname_categories.category.fantasy"},
	{nick: "Jar-Jar Binks", nickCategory: "view.nickname_categories.category.fantasy"},
	{nick: "Ganon", nickCategory: "view.nickname_categories.category.fantasy"},
	{nick: "Zelda", nickCategory: "view.nickname_categories.category.fantasy"},
	{nick: "Link", nickCategory: "view.nickname_categories.category.fantasy"},
	{nick: "George Lucas", nickCategory: "view.nickname_categories.category.literature"},
	{nick: "J.R.R. Tolkien", nickCategory: "view.nickname_categories.category.literature"},
	{nick: "Joanne K. Rowling", nickCategory: "view.nickname_categories.category.literature"},
	{nick: "Astrid Lindgren", nickCategory: "view.nickname_categories.category.literature"},
	{nick: "William Shakespeare", nickCategory: "view.nickname_categories.category.literature"},
	{nick: "Johann Wolfgang von Goethe", nickCategory: "view.nickname_categories.category.literature"},
	{nick: "Franz Kafka", nickCategory: "view.nickname_categories.category.literature"},
	{nick: "Charles Dickens", nickCategory: "view.nickname_categories.category.literature"},
	{nick: "Erich Kästner", nickCategory: "view.nickname_categories.category.literature"},
	{nick: "Friedrich von Schiller", nickCategory: "view.nickname_categories.category.literature"},
	{nick: "Hermann Hesse", nickCategory: "view.nickname_categories.category.literature"},
	{nick: "Oscar Wilde", nickCategory: "view.nickname_categories.category.literature"},
	{nick: "Edgar Allan Poe", nickCategory: "view.nickname_categories.category.literature"},
	{nick: "Mark Twain", nickCategory: "view.nickname_categories.category.literature"},
	{nick: "Fjodor Dostojewski", nickCategory: "view.nickname_categories.category.literature"},
	{nick: "Leo Tolstoi", nickCategory: "view.nickname_categories.category.literature"},
	{nick: "George Orwell", nickCategory: "view.nickname_categories.category.literature"},
	{nick: "Bertolt Brecht", nickCategory: "view.nickname_categories.category.literature"},
	{nick: "Michael Ende", nickCategory: "view.nickname_categories.category.literature"},
	{nick: "Enid Blyton", nickCategory: "view.nickname_categories.category.literature"},
	{nick: "Zeus", nickCategory: "view.nickname_categories.category.mythology"},
	{nick: "Jupiter", nickCategory: "view.nickname_categories.category.mythology"},
	{nick: "Apollo", nickCategory: "view.nickname_categories.category.mythology"},
	{nick: "Ceres", nickCategory: "view.nickname_categories.category.mythology"},
	{nick: "Chaos", nickCategory: "view.nickname_categories.category.mythology"},
	{nick: "Nyx", nickCategory: "view.nickname_categories.category.mythology"},
	{nick: "Gaia", nickCategory: "view.nickname_categories.category.mythology"},
	{nick: "Erebos", nickCategory: "view.nickname_categories.category.mythology"},
	{nick: "Hermes", nickCategory: "view.nickname_categories.category.mythology"},
	{nick: "Aphrodite", nickCategory: "view.nickname_categories.category.mythology"},
	{nick: "Kerberos", nickCategory: "view.nickname_categories.category.mythology"},
	{nick: "Eldorado", nickCategory: "view.nickname_categories.category.mythology"},
	{nick: "Erasmus", nickCategory: "view.nickname_categories.category.mythology"},
	{nick: "Kanaloa", nickCategory: "view.nickname_categories.category.mythology"},
	{nick: "Setibos", nickCategory: "view.nickname_categories.category.mythology"},
	{nick: "Sukkubus", nickCategory: "view.nickname_categories.category.mythology"},
	{nick: "Ahas", nickCategory: "view.nickname_categories.category.mythology"},
	{nick: "Philippus", nickCategory: "view.nickname_categories.category.mythology"},
	{nick: "Uriel", nickCategory: "view.nickname_categories.category.mythology"},
	{nick: "Onesimus", nickCategory: "view.nickname_categories.category.mythology"},
	{nick: "Edward Norton", nickCategory: "view.nickname_categories.category.actor"},
	{nick: "Alan Rickman", nickCategory: "view.nickname_categories.category.actor"},
	{nick: "Bud Spencer", nickCategory: "view.nickname_categories.category.actor"},
	{nick: "Robert De Niro", nickCategory: "view.nickname_categories.category.actor"},
	{nick: "Kevin Spacey", nickCategory: "view.nickname_categories.category.actor"},
	{nick: "Johnny Depp", nickCategory: "view.nickname_categories.category.actor"},
	{nick: "Mads Mikkelsen", nickCategory: "view.nickname_categories.category.actor"},
	{nick: "Christian Bale", nickCategory: "view.nickname_categories.category.actor"},
	{nick: "Clint Eastwood", nickCategory: "view.nickname_categories.category.actor"},
	{nick: "Jack Nicholson", nickCategory: "view.nickname_categories.category.actor"},
	{nick: "Charlie Chaplin", nickCategory: "view.nickname_categories.category.actor"},
	{nick: "Harrison Ford", nickCategory: "view.nickname_categories.category.actor"},
	{nick: "Morgan Freeman", nickCategory: "view.nickname_categories.category.actor"},
	{nick: "Robin Williams", nickCategory: "view.nickname_categories.category.actor"},
	{nick: "Tom Hanks", nickCategory: "view.nickname_categories.category.actor"},
	{nick: "Denzel Washington", nickCategory: "view.nickname_categories.category.actor"},
	{nick: "Bruce Willis", nickCategory: "view.nickname_categories.category.actor"},
	{nick: "Ewan McGregor", nickCategory: "view.nickname_categories.category.actor"},
	{nick: "Brad Pitt", nickCategory: "view.nickname_categories.category.actor"},
	{nick: "Patrick Steward", nickCategory: "view.nickname_categories.category.actor"},
	{nick: "Barack Obama", nickCategory: "view.nickname_categories.category.politics"},
	{nick: "Angela Merkel", nickCategory: "view.nickname_categories.category.politics"},
	{nick: "Kofi Annan", nickCategory: "view.nickname_categories.category.politics"},
	{nick: "Fidel Castro", nickCategory: "view.nickname_categories.category.politics"},
	{nick: "Michail Gorbatschow", nickCategory: "view.nickname_categories.category.politics"},
	{nick: "Elizabeth II.", nickCategory: "view.nickname_categories.category.politics"},
	{nick: "Benjamin Franklin", nickCategory: "view.nickname_categories.category.politics"},
	{nick: "Napoleon Bonaparte", nickCategory: "view.nickname_categories.category.politics"},
	{nick: "Mahatma Gandhi", nickCategory: "view.nickname_categories.category.politics"},
	{nick: "Lenin", nickCategory: "view.nickname_categories.category.politics"},
	{nick: "Jeanne d'Arc", nickCategory: "view.nickname_categories.category.politics"},
	{nick: "Vlad III. Drăculea", nickCategory: "view.nickname_categories.category.politics"},
	{nick: "Dschingis Khan", nickCategory: "view.nickname_categories.category.politics"},
	{nick: "Hernán Cortés", nickCategory: "view.nickname_categories.category.politics"},
	{nick: "Wladimir Putin", nickCategory: "view.nickname_categories.category.politics"},
	{nick: "John F. Kennedy", nickCategory: "view.nickname_categories.category.politics"},
	{nick: "Charles de Gaulle", nickCategory: "view.nickname_categories.category.politics"},
	{nick: "Willy Brandt", nickCategory: "view.nickname_categories.category.politics"},
	{nick: "Erich Honecker", nickCategory: "view.nickname_categories.category.politics"},
	{nick: "Ban Ki-moon", nickCategory: "view.nickname_categories.category.politics"}
];
